### ISSUE TITLE
Feature request: Window Titles support emojis using MacOS built-in emoji keyboard

### ISSUE THREAD

**Issue by jenniferdavidson** [tpamula/webextension-window-titler#24] opened 2019-07-09 16:06 UTC
Could Window Titles support emoji characters? I'm on a Mac, and I often use the Ctrl+Apple(Windows)+Space shortcut to bring up an emoji keyboard and add an emoji to text. I think it'd be fun and useful to have Window Titles support emoji characters.

**Comment by tpamula** [comment] 2019-07-10 09:56
Hi Jennifer,

Window Titler actually does support emojis. What kind of an issue are you having? Could you describe the current behaviour and the expected behaviour of the addon?

Emojis in the window title:
![image](https://user-images.githubusercontent.com/2989768/60959352-f27ab900-a2ff-11e9-99b6-6bff87f69001.png)

**Comment by tpamula** [comment] 2019-07-10 17:32
Hi Jennifer,

Window Titler actually does support emojis. What kind of issue are you having? Could you describe the current behaviour and the expected behaviour of the addon?

Emojis in the window title:
![image](https://user-images.githubusercontent.com/2989768/60959352-f27ab900-a2ff-11e9-99b6-6bff87f69001.png)

**Comment by jenniferdavidson** [comment] 2019-09-06 19:06
If you change the suffix of this file to .mov it is a screencap: 
[Screen Recording 2019-09-06 at 12.01.45 PM.zip](https://github.com/tpamula/webextension-window-titler/files/3585340/Screen.Recording.2019-09-06.at.12.01.45.PM.zip)

There is a built-in emoji keyboard with Mac. Here are the rough steps to reproduce the problem: 
1. Select Window Titler Icon in the Toolbar. It opens a text field to type into. 
2. Press Ctrl+Command+Space Bar to bring up the Emoji toolbar. 
3. The Window Titler text field disappears when this command is shown. I can pick an emoji, but it doesn't get populated back into the text field.

**Comment by tpamula** [comment] 2019-09-13 12:52
Thanks for clarifying.

The popup disappears because it loses focus and that's the expected default behaviour in Firefox (per [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1389749#c2)). There are related tickets on Firefox's bug tracker such as [this (already mentioned) one](https://bugzilla.mozilla.org/show_bug.cgi?id=1389749) or [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1292701). Submitting a bug report there could help in having it resolved. Since this is a Firefox bug it can't be fixed in the scope of this extension.

A maybe-not-so-handy-but-working workaround would be to copy an emoji and paste it into the Window Titler's input field.

**Comment by tpamula** [comment] 2019-09-14 14:24
Jennifer,

After some investigating it looks like the issue you have reported is related to Firefox and MacOS rather than to this extension for this bug is also present in other extensions on MacOS.

@orchee figured it out (as a Mac owner which I am not) and he even created [a ticket in Firefox's bug tracker for this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1581309).

**Closed by tpamula** 2019-09-14 14:24 UTC
Labels: Firefox issue

**Comment by tpamula** [comment] 2019-09-14 14:29
Jennifer,

After some investigating it looks like the issue you have reported is related to Firefox and MacOS rather than to this extension for this bug is also present in other extensions on MacOS.

@orchee figured it out (as a Mac owner which I am not) and he even created [a ticket in the Firefox's bug tracker for this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1581309).
